// Demo content for the Little Bit of Luxe UI kit.
// Real photography is referenced via Unsplash CDN URLs — swap freely.

window.LBL_DATA = {
  featured: {
    id: "splendido",
    eyebrow: "HOTEL REVIEW · ITALY",
    title: "A weekend at the Splendido that lived up to its name.",
    dek: "Above the harbour at Portofino, a hotel that has been quietly perfecting itself since 1901 makes the case — again — for going nowhere else.",
    author: "Eliza Marchetti",
    readTime: "9 MIN READ",
    date: "MAY 2026",
    rating: 9.4,
    cover: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?auto=format&fit=crop&w=1600&q=80",
    location: "Portofino, Italy",
    category: "Hotel Review",
  },
  articles: [
    {
      id: "pantelleria",
      eyebrow: "DISPATCHES · SICILY",
      title: "A quiet week on Pantelleria, where the wine is volcanic.",
      author: "Eliza Marchetti",
      readTime: "7 MIN READ",
      cover: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?auto=format&fit=crop&w=1200&q=80",
      category: "Dispatches",
      rating: 9.2,
      location: "Pantelleria, Italy",
    },
    {
      id: "amangiri",
      eyebrow: "HOTEL REVIEW · UTAH",
      title: "Amangiri, and the trouble with hotels you cannot stop describing.",
      author: "Tomás Reyes",
      readTime: "11 MIN READ",
      cover: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      category: "Hotel Review",
      rating: 9.5,
      location: "Canyon Point, USA",
    },
    {
      id: "kyoto",
      eyebrow: "THE EDIT · KYOTO",
      title: "Four ryokan that take the chill out of a Kyoto winter.",
      author: "The Editors",
      readTime: "12 MIN READ",
      cover: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
      category: "The Edit",
      rating: null,
      location: "Kyoto, Japan",
    },
    {
      id: "ile-de-re",
      eyebrow: "HOTEL REVIEW · FRANCE",
      title: "An old salt-merchant's house on the Île de Ré, gently re-done.",
      author: "Margaux Devine",
      readTime: "6 MIN READ",
      cover: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&w=1200&q=80",
      category: "Hotel Review",
      rating: 8.8,
      location: "Île de Ré, France",
    },
    {
      id: "uxua",
      eyebrow: "DISPATCHES · BRAZIL",
      title: "Trancoso, before the rush — and the case for a hammock economy.",
      author: "Eliza Marchetti",
      readTime: "8 MIN READ",
      cover: "https://images.unsplash.com/photo-1540202404-1b927e27fa8b?auto=format&fit=crop&w=1200&q=80",
      category: "Dispatches",
      rating: 9.0,
      location: "Trancoso, Brazil",
    },
    {
      id: "marrakesh",
      eyebrow: "GUIDE · MOROCCO",
      title: "How we'd spend three nights in Marrakesh, if we had to choose.",
      author: "Tomás Reyes",
      readTime: "9 MIN READ",
      cover: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1200&q=80",
      category: "Guides",
      rating: null,
      location: "Marrakesh, Morocco",
    },
    {
      id: "amalfi",
      eyebrow: "HOTEL REVIEW · AMALFI",
      title: "The Sirenuse keeps proving the case for staying put.",
      author: "Margaux Devine",
      readTime: "8 MIN READ",
      cover: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?auto=format&fit=crop&w=1200&q=80",
      category: "Hotel Review",
      rating: 9.6,
      location: "Positano, Italy",
    },
    {
      id: "maldives",
      eyebrow: "THE EDIT · MALDIVES",
      title: "Six over-water suites worth the long flight (and six that aren't).",
      author: "The Editors",
      readTime: "14 MIN READ",
      cover: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80",
      category: "The Edit",
      rating: null,
      location: "Maldives",
    },
  ],
  categories: ["All", "Hotel Review", "Dispatches", "The Edit", "Guides"],
  destinations: ["Italy", "France", "Japan", "USA", "Morocco", "Brazil", "Maldives", "Greece"],
};
